/*
* generated by Xtext
*/
package gpp.testing.boxmodel.operators.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BoxModelOperatorsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
