/*
 * generated by Xtext
 */
package gpp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExampleRuntimeModule extends gpp.AbstractExampleRuntimeModule {

}
