/*
 * generated by Xtext
 */
package gpp.boxmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BoxModelUiModule extends gpp.boxmodel.ui.AbstractBoxModelUiModule {
	public BoxModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
