/*
* generated by Xtext
*/
package gpp.boxmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BoxModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
