/*
 * generated by Xtext
 */
package gpp.boxmodel.defaultboxmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DefaultBoxModelDefinitionRuntimeModule extends gpp.boxmodel.defaultboxmodel.AbstractDefaultBoxModelDefinitionRuntimeModule {
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider.class;
	}
}
