/*
* generated by Xtext
*/
package gpp.ui.contentassist;

import gpp.ui.contentassist.AbstractExampleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExampleProposalProvider extends AbstractExampleProposalProvider {

}
