/*
 * generated by Xtext
 */
package gpp.boxmodel.scoping;

import org.eclipse.xtext.scoping.IScope;


import gpp.boxmodel.boxModel.ParserRuleOperatorApplication;

import gpp.boxmodel.boxModel.TerminalRuleOperatorApplication;


import gpp.boxmodel.operators.boxModelOperators.ParameterApplication;
import gpp.boxmodel.operators.scoping.BoxModelOperatorsScopeProvider;

public class BoxModelScopeProvider extends BoxModelOperatorsScopeProvider {

	@Override
	protected IScope getReferencedParameterScope(ParameterApplication ctx)
	{
		if(ctx.eContainer() == null)
		{
			return IScope.NULLSCOPE;
		}
		if(ctx.eContainer() instanceof ParserRuleOperatorApplication)
		{
			return getParameterScopeRelatedToOperator(((ParserRuleOperatorApplication)ctx.eContainer()).getOperator());
		}
		if(ctx.eContainer() instanceof TerminalRuleOperatorApplication)
		{
			return getParameterScopeRelatedToOperator(((TerminalRuleOperatorApplication)ctx.eContainer()).getOperator());
		}
		return super.getReferencedParameterScope(ctx);
		
	}
}
