/*
 * generated by Xtext
 */
package gpp.boxmodel.operators.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BoxModelOperatorsUiModule extends gpp.boxmodel.operators.ui.AbstractBoxModelOperatorsUiModule {
	public BoxModelOperatorsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
