/*
 * generated by Xtext
 */
package gpp.tests.temorary;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TemporaryTestRuntimeModule extends gpp.tests.temorary.AbstractTemporaryTestRuntimeModule {

}
