/*
 * generated by Xtext
 */
package gpp.testing.boxmodel.operators;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BoxModelOperatorsRuntimeModule extends gpp.testing.boxmodel.operators.AbstractBoxModelOperatorsRuntimeModule {

}
