/*
* generated by Xtext
*/
package gpp.testing.boxmodel.operators.ui.contentassist;

import gpp.testing.boxmodel.operators.ui.contentassist.AbstractBoxModelOperatorsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BoxModelOperatorsProposalProvider extends AbstractBoxModelOperatorsProposalProvider {

}
