/*
 * generated by Xtext
 */
package gpp.boxmodel.defaultboxmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DefaultBoxModelDefinitionUiModule extends gpp.boxmodel.defaultboxmodel.ui.AbstractDefaultBoxModelDefinitionUiModule {
	public DefaultBoxModelDefinitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
