/*
 * generated by Xtext
 */
package gpp.boxmodel.defaultboxmodel.scoping;

import org.eclipse.xtext.scoping.IScope;

import gpp.boxmodel.defaultboxmodel.defaultBoxModelDefinition.OperatorApplication;
import gpp.boxmodel.operators.boxModelOperators.ParameterApplication;
import gpp.boxmodel.operators.scoping.BoxModelOperatorsScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class DefaultBoxModelDefinitionScopeProvider extends BoxModelOperatorsScopeProvider {

	@Override
	protected IScope getReferencedParameterScope(ParameterApplication ctx)
	{
		if(ctx.eContainer() == null)
		{
			return IScope.NULLSCOPE;
		}
		if(ctx.eContainer() instanceof OperatorApplication)
		{
			return getParameterScopeRelatedToOperator(((OperatorApplication)ctx.eContainer()).getOperator());
		}
		return super.getReferencedParameterScope(ctx);
	}
}
