/*
 * generated by Xtext
 */
package gpp.boxmodel.operators;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BoxModelOperatorsRuntimeModule extends gpp.boxmodel.operators.AbstractBoxModelOperatorsRuntimeModule {
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider.class;
	}
}
