/*
 * generated by Xtext
 */
package gpp.boxmodel;

import gpp.boxmodel.naming.GppQualifiedNameProvider;
import gpp.boxmodel.scoping.GppLinkingService;
import gpp.boxmodel.scoping.GppLoadOnDemandResourceDescriptions;

import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.scoping.impl.LoadOnDemandResourceDescriptions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BoxModelRuntimeModule extends gpp.boxmodel.AbstractBoxModelRuntimeModule {
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider.class;
	}
	
	public Class<? extends LoadOnDemandResourceDescriptions> bindLoadOnDemandResourceDescriptions()
	{
		return GppLoadOnDemandResourceDescriptions.class;
	}
	
	public Class<? extends ILinkingService> bindILinkingService()
	{
		return GppLinkingService.class;
	}
	
}
