/*
 * generated by Xtext
 */
package gpp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExampleUiModule extends gpp.ui.AbstractExampleUiModule {
	public ExampleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
